using Core.DTOs; using Core.DTOs.Interfaces; using Core.Models; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using QuestPDF.Fluent; using QuestPDF.Helpers; using QuestPDF.Infrastructure;
namespace Core.Controllers;
[Authorize,ApiController,Route("api/facturacion")]
public class FacturacionController(IFacturacionProviderDTO provider):ControllerBase {
 [HttpGet("recibos")] public async Task<IActionResult> Receipts(int idSucursal,string? query=null){var branch=Branch(idSucursal);return Ok(new ApiResponse<object>{Success=true,Message="Recibos facturables.",Data=await provider.BuscarRecibosAsync(branch,query??"")});}
 [HttpPost] public async Task<IActionResult> Create(AutorizarFacturaDTO r){if(string.IsNullOrWhiteSpace(r.Nombre))return BadRequest(new ApiResponse<object>{Success=false,Message="El nombre del receptor es obligatorio."});r.IdSucursal=Branch(r.IdSucursal);try{var id=await provider.AutorizarAsync(r);return Ok(new ApiResponse<object>{Success=true,Message="Factura simulada autorizada y firmada.",Data=new{IdFactura=id}});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
 [HttpPost("abonos")] public async Task<IActionResult> InvoicePayment(FacturarAbonoDTO r){if(string.IsNullOrWhiteSpace(r.Nombre))return BadRequest(new ApiResponse<object>{Success=false,Message="El nombre del receptor es obligatorio."});r.IdSucursal=Branch(r.IdSucursal);try{var id=await provider.FacturarAbonoAsync(r);return Ok(new ApiResponse<object>{Success=true,Message="Abono facturado correctamente.",Data=new{IdFactura=id}});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
 [HttpGet] public async Task<IActionResult> Search(int idSucursal,string? query=null,DateTime? fechaDesde=null,DateTime? fechaHasta=null){var branch=Branch(idSucursal);return Ok(new ApiResponse<object>{Success=true,Message="Facturas obtenidas.",Data=await provider.BuscarAsync(branch,query??"",fechaDesde,fechaHasta)});}
 [HttpGet("{id:int}/pdf")] public async Task<IActionResult> Pdf(int id){var f=await provider.ObtenerAsync(id);if(f==null)return NotFound();QuestPDF.Settings.License=LicenseType.Community;var bytes=Document.Create(d=>d.Page(p=>{p.Size(PageSizes.A4);p.Margin(30);p.Header().Column(c=>{c.Item().Text("FACTURA ELECTRÓNICA (SIMULACIÓN)").Bold().FontSize(20).FontColor("#0f766e");c.Item().Text($"{f.NumeroFactura} · {f.SucursalNombre}");});p.Content().PaddingTop(20).Column(c=>{c.Spacing(12);c.Item().Border(1).Padding(12).Text($"Receptor: {f.NombreReceptor}\nNIT: {f.NitReceptor}\nDirección: {f.DireccionReceptor??"—"}\nAutorización: {f.NumeroAutorizacion}\nCertificada y firmada: {f.FechaCertificacion:dd/MM/yyyy HH:mm}");foreach(var x in f.Detalles)c.Item().Row(r=>{r.RelativeItem().Text(x.ProductoNombre);r.ConstantItem(50).Text(x.Cantidad.ToString());r.ConstantItem(90).AlignRight().Text($"Q {x.Subtotal:0.00}");});c.Item().BorderTop(1).PaddingTop(10).AlignRight().Text($"TOTAL Q {f.Total:0.00}").Bold().FontSize(16);c.Item().Text($"Recibo relacionado: {f.NumeroRecibo}").FontColor(Colors.Grey.Darken1);});p.Footer().AlignCenter().Text("Documento simulado pendiente de integración con certificador fiscal.");})).GeneratePdf();return File(bytes,"application/pdf",$"{f.NumeroFactura}.pdf");}
 private int Branch(int requested){var claim=User.FindFirst("id_sucursal")?.Value??User.FindFirst("IdSucursal")?.Value;return int.TryParse(claim,out var assigned)&&assigned>0?assigned:requested;}
}
