using System.Security.Claims;using Core.DTOs;using Core.DTOs.Interfaces;using Core.Models;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;
namespace Core.Controllers;[Authorize,ApiController,Route("api/operaciones")]
public class OperacionesController(IOperacionProviderDTO p):ControllerBase{private int UserId()=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier)??User.FindFirst("id_usuario")?.Value,out var id)?id:0;private int Branch(int requested){var c=User.FindFirst("id_sucursal")?.Value;return int.TryParse(c,out var id)&&id>0?id:requested;}
[HttpGet("caja")]public async Task<IActionResult>Caja(int idSucursal)=>Ok(new ApiResponse<object>{Success=true,Message="Estado de caja.",Data=await p.EstadoCaja(UserId(),Branch(idSucursal))});
[HttpPost("caja/abrir")]public async Task<IActionResult>Abrir(CajaMovimientoDTO x){try{await p.AbrirCaja(UserId(),Branch(x.IdSucursal),x.Monto);return Ok(new ApiResponse<object>{Success=true,Message="Caja abierta correctamente."});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
[HttpPost("caja/salidas")]public async Task<IActionResult>Salida(SalidaCajaRequestDTO x){try{await p.RegistrarSalidaCaja(UserId(),Branch(x.IdSucursal),x.Monto,x.Concepto,x.Observaciones);return Ok(new ApiResponse<object>{Success=true,Message="Salida registrada correctamente."});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
[HttpPost("caja/cerrar")]public async Task<IActionResult>Cerrar(CajaMovimientoDTO x){try{var cierre=await p.CerrarCaja(UserId(),Branch(x.IdSucursal),x.Monto,x.Observaciones);return Ok(new ApiResponse<object>{Success=true,Message="Caja cerrada correctamente.",Data=cierre});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
[HttpGet("caja/movimientos")]public async Task<IActionResult>Movimientos(int idSucursal,int? idSesion=null)=>Ok(new ApiResponse<object>{Success=true,Message="Movimientos de caja.",Data=await p.MovimientosCaja(UserId(),Branch(idSucursal),idSesion)});
[HttpGet("caja/cierres")]public async Task<IActionResult>Cierres(int idSucursal,DateTime? fechaDesde=null,DateTime? fechaHasta=null)=>Ok(new ApiResponse<object>{Success=true,Message="Cierres de caja.",Data=await p.CierresCaja(Branch(idSucursal),fechaDesde,fechaHasta)});
[HttpGet("clientes")]public async Task<IActionResult>Clientes(int idSucursal,string? query=null)=>Ok(new ApiResponse<object>{Success=true,Message="Clientes.",Data=await p.Clientes(query??"",Branch(idSucursal))});
[HttpPost("clientes")]public async Task<IActionResult>Crear(ClienteGestionDTO x){if(string.IsNullOrWhiteSpace(x.Nombre))return BadRequest(new ApiResponse<object>{Success=false,Message="El nombre es obligatorio."});try{var id=await p.CrearCliente(x);return Ok(new ApiResponse<object>{Success=true,Message="Cliente creado.",Data=new{IdCliente=id}});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
[HttpPut("clientes/{id:int}")]public async Task<IActionResult>Actualizar(int id,ClienteGestionDTO x){if(string.IsNullOrWhiteSpace(x.Nombre))return BadRequest(new ApiResponse<object>{Success=false,Message="El nombre es obligatorio."});try{x.IdCliente=id;await p.ActualizarCliente(x);return Ok(new ApiResponse<object>{Success=true,Message="Cliente actualizado."});}catch(Exception e){return BadRequest(new ApiResponse<object>{Success=false,Message=e.Message});}}
[HttpGet("clientes/{id:int}/historial")]public async Task<IActionResult>Historial(int id,int idSucursal,DateTime? fechaDesde=null,DateTime? fechaHasta=null)=>Ok(new ApiResponse<object>{Success=true,Message="Historial.",Data=await p.Historial(id,Branch(idSucursal),fechaDesde,fechaHasta)});
[HttpGet("reportes/{tipo}")]public async Task<IActionResult>Reporte(string tipo,int idSucursal,DateTime fechaDesde,DateTime fechaHasta){if(tipo is not("ventas" or "inventario" or "cobros" or "caja"))return BadRequest();return Ok(new ApiResponse<object>{Success=true,Message="Reporte generado.",Data=await p.Reporte(tipo,Branch(idSucursal),fechaDesde,fechaHasta)});}}
