using System.Security.Claims;
using Core.DTOs;
using Core.DTOs.Interfaces;
using Core.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Core.Services;
namespace Core.Controllers;
[Authorize,ApiController,Route("api/trabajadores")]
public class TrabajadoresController(ITrabajadorProviderDTO provider):ControllerBase
{
 private int UserId()=>int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),out var id)?id:0;
 [HttpGet("modulos")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>Modulos()=>Ok(new ApiResponse<object>{Success=true,Data=await provider.Modulos()});
 [HttpGet("usuarios")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>Usuarios([FromQuery]string query="")=>Ok(new ApiResponse<object>{Success=true,Data=await provider.Usuarios(query)});
 [HttpPost("usuarios")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>GuardarUsuario(UsuarioGestionDTO x){try{if(string.IsNullOrWhiteSpace(x.Nombre)||string.IsNullOrWhiteSpace(x.Apellidos)||string.IsNullOrWhiteSpace(x.Username))return BadRequest(Fail("Nombres, apellidos y usuario son obligatorios."));if(!string.IsNullOrWhiteSpace(x.Telefono)&&!System.Text.RegularExpressions.Regex.IsMatch(x.Telefono,"^[0-9]{8}$"))return BadRequest(Fail("El teléfono debe contener exactamente 8 números."));if(!string.IsNullOrWhiteSpace(x.Correo)&&!System.Net.Mail.MailAddress.TryCreate(x.Correo,out _))return BadRequest(Fail("El correo no es válido."));if(x.Rol.Equals("Encargado",StringComparison.OrdinalIgnoreCase)&&x.FechaExpiracionPassword is DateTime expiry&&expiry.Date<DateTime.Today)return BadRequest(Fail("La vigencia no puede ser anterior a hoy."));if(x.IdUsuario.HasValue&&!string.IsNullOrWhiteSpace(x.Password))return BadRequest(Fail("Cambia la contraseña desde el botón independiente de la cuenta."));if(!string.IsNullOrEmpty(x.Password)&&!PasswordPolicy.IsValid(x.Password))return BadRequest(Fail(PasswordPolicy.Message));if(!x.IdUsuario.HasValue&&string.IsNullOrEmpty(x.Password))return BadRequest(Fail("La contraseña es obligatoria para un usuario nuevo."));var hash=string.IsNullOrEmpty(x.Password)?null:BCrypt.Net.BCrypt.HashPassword(x.Password);var id=await provider.GuardarUsuario(x,hash);return Ok(new ApiResponse<object>{Success=true,Message="Usuario guardado.",Data=new{IdUsuario=id}});}catch(Exception e){return BadRequest(Fail(e.Message));}}
 [HttpGet] public async Task<IActionResult>Trabajadores([FromQuery]int? idSucursal,[FromQuery]string query="",[FromQuery]bool soloActivos=false)=>Ok(new ApiResponse<object>{Success=true,Data=await provider.Trabajadores(idSucursal,query,soloActivos)});
 [HttpPost][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>GuardarTrabajador(TrabajadorGestionDTO x){try{if(!string.IsNullOrWhiteSpace(x.Correo)&&!System.Net.Mail.MailAddress.TryCreate(x.Correo,out _))return BadRequest(Fail("El correo no es válido."));if(!string.IsNullOrWhiteSpace(x.Telefono)&&!System.Text.RegularExpressions.Regex.IsMatch(x.Telefono,"^[0-9]{8}$"))return BadRequest(Fail("El teléfono debe contener exactamente 8 números."));if(!string.IsNullOrWhiteSpace(x.Dpi)&&!System.Text.RegularExpressions.Regex.IsMatch(x.Dpi,"^[0-9]{13}$"))return BadRequest(Fail("El DPI debe contener exactamente 13 números."));var id=await provider.GuardarTrabajador(x,UserId());return Ok(new ApiResponse<object>{Success=true,Message="Trabajador guardado.",Data=new{IdVendedor=id}});}catch(Exception e){return BadRequest(Fail(e.Message));}}
 [HttpPost("evaluaciones")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>Evaluar(EvaluacionTrabajadorRequestDTO x){try{var id=await provider.GuardarEvaluacion(x,UserId());return Ok(new ApiResponse<object>{Success=true,Message="Evaluación registrada.",Data=new{IdEvaluacion=id}});}catch(Exception e){return BadRequest(Fail(e.Message));}}
 [HttpGet("kpis")] public async Task<IActionResult>Kpis(int? idSucursal,DateTime fechaDesde,DateTime fechaHasta)=>Ok(new ApiResponse<object>{Success=true,Data=await provider.Kpis(idSucursal,fechaDesde,fechaHasta)});
 [HttpGet("ventas")] public async Task<IActionResult>Ventas(int idSucursal,int? idVendedor,DateTime fechaDesde,DateTime fechaHasta)=>Ok(new ApiResponse<object>{Success=true,Data=await provider.Ventas(idSucursal,idVendedor,fechaDesde,fechaHasta)});
 [HttpGet("historico")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>Historico(int? idSucursal=null,int? idVendedor=null,string query="",string tipo="",DateTime? fechaDesde=null,DateTime? fechaHasta=null,int pagina=1,int tamanoPagina=30){var rows=await provider.Historial(idSucursal,idVendedor,query.Trim(),tipo.Trim(),fechaDesde,fechaHasta,Math.Max(1,pagina),Math.Clamp(tamanoPagina,1,100));return Ok(new ApiResponse<object>{Success=true,Message="Histórico de trabajadores obtenido.",Data=new{Registros=rows,Total=rows.FirstOrDefault()?.TotalRegistros??0,Pagina=Math.Max(1,pagina),TamanoPagina=Math.Clamp(tamanoPagina,1,100)}});}
 [HttpGet("planilla")] public async Task<IActionResult>Planilla(int? idSucursal,DateTime fechaDesde,DateTime fechaHasta){if(fechaHasta.Date<fechaDesde.Date)return BadRequest(Fail("La fecha final no puede ser anterior a la fecha inicial."));if((fechaHasta.Date-fechaDesde.Date).TotalDays>366)return BadRequest(Fail("El periodo de planilla no puede superar un ano."));return Ok(new ApiResponse<object>{Success=true,Message="Planilla calculada.",Data=await provider.Planilla(idSucursal,fechaDesde.Date,fechaHasta.Date)});}
 [HttpGet("{idVendedor:int}/configuracion-pago")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>ConfiguracionPago(int idVendedor){var data=await provider.ConfiguracionPago(idVendedor);return data is null?NotFound(Fail("El trabajador no existe.")):Ok(new ApiResponse<object>{Success=true,Data=data});}
 [HttpPut("configuracion-pago")][Authorize(Roles="demo,Demo,superusuario,Superusuario,admin,Admin,Administrador,administrador")] public async Task<IActionResult>GuardarConfiguracionPago(GuardarConfiguracionPagoDTO x){try{if(x.IdVendedor<=0)return BadRequest(Fail("Selecciona un trabajador."));if(x.SalarioMensual<=0)return BadRequest(Fail("El salario mensual debe ser mayor que cero."));if(x.SalarioMensual>1000000)return BadRequest(Fail("El salario mensual excede el limite permitido."));x.Bonos=(x.Bonos??[]).Distinct().Where(id=>id>0).ToList();await provider.GuardarConfiguracionPago(x,UserId());return Ok(new ApiResponse<object>{Success=true,Message="Sueldo y bonos actualizados."});}catch(Exception e){return BadRequest(Fail(e.Message));}}
 private static ApiResponse<object> Fail(string message)=>new(){Success=false,Message=message};
}
