namespace Core.DTOs;

public class CobroClienteDTO { public int IdClienteCredito{get;set;} public int IdCliente{get;set;} public string Cliente{get;set;}=""; public string? Nit{get;set;} public string? Telefono{get;set;} public decimal LimiteCredito{get;set;} public decimal SaldoPendiente{get;set;} public decimal CreditoDisponible{get;set;} public int CuentasPendientes{get;set;} public int CuotasVencidas{get;set;} public DateTime? ProximoVencimiento{get;set;} public bool Activo{get;set;} public string? EstadoAutorizacion{get;set;} public DateTime? FechaCambioEstado{get;set;} }
public class CuentaPendienteCobroDTO { public int IdCuenta{get;set;} public int IdCliente{get;set;} public string Cliente{get;set;}=""; public string? Nit{get;set;} public string? Correo{get;set;} public string? Telefono{get;set;} public int IdReciboOrigen{get;set;} public string NotaCredito{get;set;}=""; public DateTime FechaVenta{get;set;} public decimal TotalVenta{get;set;} public decimal MontoInicial{get;set;} public decimal SaldoPendiente{get;set;} public int NumeroCuotas{get;set;} public int CuotasPagadas{get;set;} public DateTime? ProximoVencimiento{get;set;} }
public class EstadoCuentaResumenDTO { public int IdCliente{get;set;} public string Cliente{get;set;}=""; public string? Nit{get;set;} public string? Telefono{get;set;} public decimal LimiteCredito{get;set;} public decimal SaldoPendiente{get;set;} public decimal CreditoDisponible{get;set;} public bool Activo{get;set;} public string? EstadoAutorizacion{get;set;} public DateTime? FechaCambioEstado{get;set;} }
public class EstadoCuentaCreditoDTO { public int IdCuenta{get;set;} public string NotaCredito{get;set;}=""; public DateTime Fecha{get;set;} public decimal Total{get;set;} public decimal MontoInicial{get;set;} public decimal SaldoPendiente{get;set;} public int NumeroCuotas{get;set;} public string Estado{get;set;}=""; }
public class EstadoCuentaMovimientoDTO { public int IdMovimiento{get;set;} public int IdCuenta{get;set;} public DateTime Fecha{get;set;} public string Tipo{get;set;}=""; public string Documento{get;set;}=""; public decimal Debito{get;set;} public decimal Credito{get;set;} public string Estado{get;set;}=""; public DateTime? FechaVencimiento{get;set;} }
public class EstadoCuentaDTO { public EstadoCuentaResumenDTO? Resumen{get;set;} public List<EstadoCuentaCreditoDTO> Creditos{get;set;}=[]; public List<EstadoCuentaMovimientoDTO> Movimientos{get;set;}=[]; }
public class RegistrarAbonoDTO { public int IdCuenta{get;set;} public int IdSucursal{get;set;} public decimal Monto{get;set;} public string MetodoPago{get;set;}=""; public string? Referencia{get;set;} public string? Correo{get;set;} public string? Telefono{get;set;} }
public class AbonoReciboDTO { public int IdAbono{get;set;} public string NumeroAbono{get;set;}=""; public DateTime Fecha{get;set;} public decimal Monto{get;set;} public string MetodoPago{get;set;}=""; public string? Referencia{get;set;} public decimal SaldoAnterior{get;set;} public decimal SaldoPosterior{get;set;} public string NotaCredito{get;set;}=""; public string Cliente{get;set;}=""; public string? Nit{get;set;} public string? Correo{get;set;} public string? Telefono{get;set;} public string Sucursal{get;set;}=""; public string? Usuario{get;set;} public int IdCuenta{get;set;} public decimal TotalCredito{get;set;} public decimal PagadoAcumulado{get;set;} }
public class AbonoConsultaDTO { public int IdAbono{get;set;} public string NumeroAbono{get;set;}=""; public DateTime Fecha{get;set;} public decimal Monto{get;set;} public string MetodoPago{get;set;}=""; public string Cliente{get;set;}=""; public string? Nit{get;set;} public int? IdFactura{get;set;} public string? NumeroFactura{get;set;} public bool EsFacturada{get;set;} }
public class AutorizacionCreditoDTO { public int IdCliente{get;set;} public string Cliente{get;set;}=""; public string? Nit{get;set;} public string? Telefono{get;set;} public int? IdClienteCredito{get;set;} public decimal? LimiteCredito{get;set;} public int DiasMaximosPago{get;set;}=30; public DateTime? FechaVencimientoAutorizacion{get;set;} public string? Observaciones{get;set;} public bool Activo{get;set;} public decimal SaldoPendiente{get;set;} public string EstadoAutorizacion{get;set;}="Sin autorización"; }
public class GuardarAutorizacionCreditoDTO { public int IdCliente{get;set;} public decimal LimiteCredito{get;set;} public int DiasMaximosPago{get;set;} public DateTime? FechaVencimientoAutorizacion{get;set;} public string? Observaciones{get;set;} public bool Activo{get;set;}=true; }
