namespace Core.DTOs;
public class CajaEstadoDTO { public int IdSesion{get;set;} public DateTime FechaApertura{get;set;} public DateTime? FechaCierre{get;set;} public decimal MontoApertura{get;set;} public decimal? MontoCierre{get;set;} public decimal? MontoEsperado{get;set;} public decimal? Diferencia{get;set;} public string? Observaciones{get;set;} public decimal VentasEfectivo{get;set;} public decimal VentasTarjeta{get;set;} public decimal VentasTransferencia{get;set;} public decimal VentasCredito{get;set;} public decimal VentasTotales{get;set;} public decimal ComprasEfectivo{get;set;} public decimal AbonosEfectivo{get;set;} public decimal SalidasEfectivo{get;set;} }
public class CajaMovimientoDTO { public int IdSucursal{get;set;} public decimal Monto{get;set;} public string? Observaciones{get;set;} }
public class SalidaCajaRequestDTO { public int IdSucursal{get;set;} public decimal Monto{get;set;} public string Concepto{get;set;}=""; public string? Observaciones{get;set;} }
public class MovimientoCajaDTO { public string Tipo{get;set;}=""; public string Numero{get;set;}=""; public DateTime Fecha{get;set;} public string MetodoPago{get;set;}=""; public decimal Monto{get;set;} public string Estado{get;set;}=""; }
public class CierreCajaDTO { public int IdSesion{get;set;} public string NumeroCierre{get;set;}=""; public DateTime? FechaApertura{get;set;} public DateTime FechaCierre{get;set;} public decimal MontoApertura{get;set;} public decimal MontoEsperado{get;set;} public decimal MontoCierre{get;set;} public decimal Diferencia{get;set;} public string? Observaciones{get;set;} public string? Usuario{get;set;} }
public class ClienteGestionDTO { public int IdCliente{get;set;} public string Nombre{get;set;}=""; public string? Nit{get;set;} public string? Telefono{get;set;} public string? Correo{get;set;} public string? Direccion{get;set;} public DateTime? FechaNacimiento{get;set;} public int? Edad{get;set;} public int Compras{get;set;} public decimal TotalComprado{get;set;} public bool TieneEstadoCrediticio{get;set;} public string? EstadoCredito{get;set;} }
public class HistorialClienteDTO { public int IdVenta{get;set;} public DateTime Fecha{get;set;} public decimal Total{get;set;} public string TipoPago{get;set;}=""; public int? IdRecibo{get;set;} public string? NumeroRecibo{get;set;} public string? EstadoRecibo{get;set;} public int? IdFactura{get;set;} public string? NumeroFactura{get;set;} public string? EstadoFactura{get;set;} public decimal SaldoPendiente{get;set;} }
public class ReporteFilaDTO { public DateTime? Fecha{get;set;} public string? Codigo{get;set;} public string Categoria{get;set;}=""; public decimal Registros{get;set;} public decimal Total{get;set;} }
