namespace Core.DTOs;

public class ModuloSistemaDTO { public int IdModulo{get;set;} public string Codigo{get;set;}=""; public string Nombre{get;set;}=""; public int Orden{get;set;} }
public class UsuarioGestionDTO { public int? IdUsuario{get;set;} public string Nombre{get;set;}=""; public string? Apellidos{get;set;} public string? Telefono{get;set;} public string Username{get;set;}=""; public string? Password{get;set;} public string? Correo{get;set;} public DateTime? FechaExpiracionPassword{get;set;} public string Rol{get;set;}="Encargado"; public int? IdSucursal{get;set;} public string? Sucursal{get;set;} public bool Activo{get;set;}=true; public string Permisos{get;set;}=""; }
public class TrabajadorGestionDTO { public int? IdVendedor{get;set;} public string Nombre{get;set;}=""; public string? Telefono{get;set;} public string? Correo{get;set;} public string? Dpi{get;set;} public string? Puesto{get;set;} public DateTime? FechaIngreso{get;set;} public int IdSucursal{get;set;} public string? Sucursal{get;set;} public bool Activo{get;set;}=true; public int Ventas{get;set;} public decimal TotalVendido{get;set;} }
public class PreguntaEvaluacionDTO { public string Pregunta{get;set;}=""; public byte Puntuacion{get;set;}=5; }
public class EvaluacionTrabajadorRequestDTO { public int IdVendedor{get;set;} public DateTime PeriodoDesde{get;set;} public DateTime PeriodoHasta{get;set;} public byte Puntualidad{get;set;} public byte ServicioCliente{get;set;} public byte CumplimientoMetas{get;set;} public byte TrabajoEquipo{get;set;} public List<PreguntaEvaluacionDTO> Preguntas{get;set;}=[]; public string? Observaciones{get;set;} }
public class KpiTrabajadorDTO { public int IdVendedor{get;set;} public string Trabajador{get;set;}=""; public string? Puesto{get;set;} public string? Sucursal{get;set;} public int Ventas{get;set;} public decimal TotalVendido{get;set;} public decimal VentaPromedio{get;set;} public decimal PromedioEvaluacion{get;set;} }
public class VentaTrabajadorDTO { public int IdVenta{get;set;} public DateTime Fecha{get;set;} public int IdVendedor{get;set;} public string Trabajador{get;set;}=""; public string? Cliente{get;set;} public string? Recibo{get;set;} public string? MetodoPago{get;set;} public decimal Total{get;set;} public string? Estado{get;set;} }
public class HistorialTrabajadorDTO { public string IdEvento{get;set;}=""; public DateTime Fecha{get;set;} public int IdVendedor{get;set;} public string Trabajador{get;set;}=""; public int? IdSucursal{get;set;} public string? Sucursal{get;set;} public string Tipo{get;set;}=""; public string? Documento{get;set;} public string? Detalle{get;set;} public decimal? Monto{get;set;} public decimal? Puntuacion{get;set;} public string? Estado{get;set;} public string Usuario{get;set;}="Sistema"; public int TotalRegistros{get;set;} }
