// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Abono
{
    public int IdAbono { get; set; }

    public int IdCuenta { get; set; }

    public DateTime? Fecha { get; set; }

    public decimal Monto { get; set; }

    public virtual CuentaCobrar IdCuentaNavigation { get; set; }
}