// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Cliente
{
    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public string Direccion { get; set; }

    public string Nit { get; set; }

    public virtual ICollection<Ventum> Venta { get; set; } = new List<Ventum>();
}