// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Compra
{
    public int IdCompra { get; set; }

    public DateTime? Fecha { get; set; }

    public decimal Total { get; set; }

    public int IdProveedor { get; set; }

    public virtual ICollection<DetalleCompra> DetalleCompras { get; set; } = new List<DetalleCompra>();

    public virtual Proveedor IdProveedorNavigation { get; set; }
}