// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class CuentaCobrar
{
    public int IdCuenta { get; set; }

    public int IdVenta { get; set; }

    public decimal SaldoPendiente { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<Abono> Abonos { get; set; } = new List<Abono>();

    public virtual Ventum IdVentaNavigation { get; set; }
}