// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class DetalleTraslado
{
    public int IdDetalleTraslado { get; set; }

    public int IdTraslado { get; set; }

    public int IdProducto { get; set; }

    public int Cantidad { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Traslado IdTrasladoNavigation { get; set; }
}