// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Factura
{
    public int IdFactura { get; set; }

    public string NumeroFactura { get; set; }

    public DateTime? FechaEmision { get; set; }

    public decimal Total { get; set; }

    public string Estado { get; set; }

    public int IdVenta { get; set; }

    public virtual Ventum IdVentaNavigation { get; set; }

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();
}