// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Inventario
{
    public int IdInventario { get; set; }

    public int IdSucursal { get; set; }

    public int IdProducto { get; set; }

    public int Stock { get; set; }

    public virtual Producto IdProductoNavigation { get; set; }

    public virtual Sucursal IdSucursalNavigation { get; set; }
}