// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Recibo
{
    public int IdRecibo { get; set; }

    public string NumeroRecibo { get; set; }

    public DateTime? FechaPago { get; set; }

    public decimal Monto { get; set; }

    public string MetodoPago { get; set; }

    public string NumeroComprobante { get; set; }

    public int IdFactura { get; set; }

    public virtual Factura IdFacturaNavigation { get; set; }
}