// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Sucursal
{
    public int IdSucursal { get; set; }

    public string Nombre { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public virtual ICollection<Inventario> Inventarios { get; set; } = new List<Inventario>();

    public virtual ICollection<Recibo> Recibos { get; set; } = new List<Recibo>();

    public virtual ICollection<Traslado> TrasladoIdSucursalDestinoNavigations { get; set; } = new List<Traslado>();

    public virtual ICollection<Traslado> TrasladoIdSucursalOrigenNavigations { get; set; } = new List<Traslado>();

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();

    public virtual ICollection<Vendedor> Vendedors { get; set; } = new List<Vendedor>();
}
