// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Traslado
{
    public int IdTraslado { get; set; }

    public int IdSucursalOrigen { get; set; }

    public int IdSucursalDestino { get; set; }

    public DateTime? Fecha { get; set; }

    public string Estado { get; set; }

    public virtual ICollection<DetalleTraslado> DetalleTraslados { get; set; } = new List<DetalleTraslado>();

    public virtual Sucursal IdSucursalDestinoNavigation { get; set; }

    public virtual Sucursal IdSucursalOrigenNavigation { get; set; }
}