// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Usuario
{
    public int IdUsuario { get; set; }

    public string Nombre { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Rol { get; set; }

    public int IdSucursal { get; set; }

    public virtual ICollection<Bitacora> Bitacoras { get; set; } = new List<Bitacora>();

    public virtual Sucursal IdSucursalNavigation { get; set; }

    public virtual ICollection<SesionCaja> SesionCajas { get; set; } = new List<SesionCaja>();
}