// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Vendedor
{
    public int IdVendedor { get; set; }

    public string Nombre { get; set; }

    public string Telefono { get; set; }

    public int? IdSucursal { get; set; }

    public virtual Sucursal IdSucursalNavigation { get; set; }

    public virtual ICollection<Ventum> Venta { get; set; } = new List<Ventum>();
}
