// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Core.Models;

public partial class Ventum
{
    public int IdVenta { get; set; }

    public DateTime? Fecha { get; set; }

    public decimal Total { get; set; }

    public string TipoPago { get; set; }

    public int IdCliente { get; set; }

    public int IdVendedor { get; set; }

    public int IdSesion { get; set; }

    public virtual ICollection<CuentaCobrar> CuentaCobrars { get; set; } = new List<CuentaCobrar>();

    public virtual ICollection<DetalleVentum> DetalleVenta { get; set; } = new List<DetalleVentum>();

    public virtual ICollection<Factura> Facturas { get; set; } = new List<Factura>();

    public virtual Cliente IdClienteNavigation { get; set; }

    public virtual SesionCaja IdSesionNavigation { get; set; }

    public virtual Vendedor IdVendedorNavigation { get; set; }
}