CREATE OR ALTER PROCEDURE dbo.sp_registrar_salida_inventario_core @IdSucursal INT,@IdUsuario INT,@Motivo VARCHAR(40),@Observaciones VARCHAR(500)=NULL,@Detalles NVARCHAR(MAX)
AS BEGIN SET NOCOUNT ON;SET XACT_ABORT ON;IF NOT EXISTS(SELECT 1 FROM dbo.motivo_salida_inventario WHERE codigo=@Motivo AND activo=1) THROW 50501,'Selecciona un motivo válido.',1;DECLARE @D TABLE(IdProducto INT,Cantidad INT);INSERT @D SELECT IdProducto,Cantidad FROM OPENJSON(@Detalles)WITH(IdProducto INT '$.IdProducto',Cantidad INT '$.Cantidad');IF NOT EXISTS(SELECT 1 FROM @D WHERE IdProducto IS NOT NULL AND Cantidad IS NOT NULL) THROW 50502,'Agrega al menos un producto.',1;IF EXISTS(SELECT 1 FROM @D d LEFT JOIN dbo.inventario i ON i.id_producto=d.IdProducto AND i.id_sucursal=@IdSucursal WHERE d.Cantidad<=0 OR i.id_inventario IS NULL OR i.stock<d.Cantidad) THROW 50503,'Uno de los productos no tiene existencia suficiente.',1;BEGIN TRANSACTION;INSERT dbo.salida_inventario(numero_salida,id_sucursal,id_usuario,motivo,observaciones)VALUES('PENDIENTE',@IdSucursal,@IdUsuario,@Motivo,NULLIF(LTRIM(RTRIM(@Observaciones)),''));DECLARE @Id INT=SCOPE_IDENTITY();UPDATE dbo.salida_inventario SET numero_salida=CONCAT('SAL-',CONVERT(CHAR(8),GETDATE(),112),'-',RIGHT('000000'+CAST(@Id AS VARCHAR(10)),6)) WHERE id_salida=@Id;INSERT dbo.detalle_salida_inventario(id_salida,id_producto,cantidad)SELECT @Id,IdProducto,Cantidad FROM @D;UPDATE i SET stock=i.stock-d.Cantidad FROM dbo.inventario i JOIN @D d ON d.IdProducto=i.id_producto WHERE i.id_sucursal=@IdSucursal;COMMIT;SELECT @Id;END
GO
CREATE OR ALTER PROCEDURE dbo.sp_listar_salidas_inventario_core @IdSucursal INT,@Query VARCHAR(100)=''
AS BEGIN SET NOCOUNT ON;SELECT s.id_salida IdSalida,s.numero_salida NumeroSalida,s.fecha,COALESCE(ms.nombre,s.motivo) motivo,s.observaciones,u.nombre Usuario,SUM(d.cantidad) Unidades,COUNT(*) Productos FROM dbo.salida_inventario s JOIN dbo.detalle_salida_inventario d ON d.id_salida=s.id_salida LEFT JOIN dbo.usuario u ON u.id_usuario=s.id_usuario LEFT JOIN dbo.motivo_salida_inventario ms ON ms.codigo=s.motivo WHERE s.id_sucursal=@IdSucursal AND (@Query='' OR s.numero_salida LIKE '%'+@Query+'%' OR COALESCE(ms.nombre,s.motivo) LIKE '%'+@Query+'%' OR ISNULL(s.observaciones,'') LIKE '%'+@Query+'%') GROUP BY s.id_salida,s.numero_salida,s.fecha,COALESCE(ms.nombre,s.motivo),s.observaciones,u.nombre ORDER BY s.fecha DESC;END
GO
IF OBJECT_ID('dbo.sp_registrar_salida_inventario','SN') IS NOT NULL DROP SYNONYM dbo.sp_registrar_salida_inventario;
IF OBJECT_ID('dbo.sp_listar_salidas_inventario','SN') IS NOT NULL DROP SYNONYM dbo.sp_listar_salidas_inventario;
GO
CREATE SYNONYM dbo.sp_registrar_salida_inventario FOR dbo.sp_registrar_salida_inventario_core;
CREATE SYNONYM dbo.sp_listar_salidas_inventario FOR dbo.sp_listar_salidas_inventario_core;
GO
