import { useState } from 'react';
import { Download, Search, X } from 'lucide-react';
import axiosClient from '../api/axiosClient';
import { useAuth } from '../context/AuthContext';
import NotificationToast from '../components/NotificationToast';

const money = new Intl.NumberFormat('es-GT', { style: 'currency', currency: 'GTQ' });
const formatDate = value => value ? new Date(value).toLocaleDateString('es-GT') : '—';

export default function CobrosPage({ mode = 'list' }) {
    const { selectedSucursalId, isAdministrator } = useAuth();
    if (mode === 'statement') return <EstadoCuenta branch={selectedSucursalId} />;
    if (mode === 'pay') return <PagarAbono branch={selectedSucursalId} />;
    if (mode === 'authorize') return isAdministrator ? <Autorizar /> : <Page title="Autorizar crédito"><Empty text="Esta opción está disponible únicamente para administradores." /></Page>;
    return <Listado branch={selectedSucursalId} />;
}

function Listado({ branch }) {
    const [filters, setFilters] = useState({ query: '', orden: 'deuda_desc', soloConDeuda: false });
    const [rows, setRows] = useState([]);
    const [loading, setLoading] = useState(false);
    const load = async () => { setLoading(true); try { const response = await axiosClient.get('/cobros', { params: { idSucursal: branch, ...filters } }); setRows(response.data.data || []); } finally { setLoading(false); } };
    return <Page title="Listado de cobros">
        <SearchBar value={filters.query} setValue={query => setFilters({ ...filters, query })} search={load} loading={loading}>
            <select className="input w-48" value={filters.orden} onChange={event => setFilters({ ...filters, orden: event.target.value })}><option value="deuda_desc">Mayor deuda</option><option value="deuda_asc">Menor deuda</option><option value="nombre_asc">Nombre A-Z</option><option value="nombre_desc">Nombre Z-A</option></select>
            <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={filters.soloConDeuda} onChange={event => setFilters({ ...filters, soloConDeuda: event.target.checked })} />Solo con deuda</label>
        </SearchBar>
        <Table headers={[<button key="cliente" onClick={() => setFilters({ ...filters, orden: filters.orden === 'nombre_asc' ? 'nombre_desc' : 'nombre_asc' })}>Cliente ↕</button>, 'NIT', 'Límite', <button key="saldo" onClick={() => setFilters({ ...filters, orden: filters.orden === 'deuda_desc' ? 'deuda_asc' : 'deuda_desc' })}>Saldo pendiente ↕</button>, 'Disponible', 'Cuotas vencidas', 'Próximo pago']} empty={!rows.length}>
            {rows.map(row => <tr key={row.idCliente}><Cell strong>{row.cliente}</Cell><Cell>{row.nit || 'CF'}</Cell><Cell right>{money.format(row.limiteCredito)}</Cell><Cell right strong>{money.format(row.saldoPendiente)}</Cell><Cell right>{money.format(row.creditoDisponible)}</Cell><Cell right>{row.cuotasVencidas}</Cell><Cell>{formatDate(row.proximoVencimiento)}</Cell></tr>)}
        </Table>
    </Page>;
}

function EstadoCuenta({ branch }) {
    const [query, setQuery] = useState(''); const [clients, setClients] = useState([]); const [selected, setSelected] = useState(null); const [state, setState] = useState(null); const [range, setRange] = useState({ fechaDesde: '', fechaHasta: '' });
    const search = async () => { const response = await axiosClient.get('/cobros', { params: { idSucursal: branch, query, orden: 'nombre_asc' } }); setClients(response.data.data || []); setState(null); };
    const consult = async client => { setSelected(client); const response = await axiosClient.get('/cobros/estado-cuenta', { params: { idSucursal: branch, idCliente: client.idCliente, ...range } }); setState(response.data.data); };
    const excel = async () => { const response = await axiosClient.get('/cobros/estado-cuenta/excel', { params: { idSucursal: branch, idCliente: selected.idCliente, ...range }, responseType: 'blob' }); download(response.data, `estado-cuenta-${selected.cliente}.xlsx`); };
    return <Page title="Estado de cuenta">
        <section className="grid gap-3 border bg-white p-5 md:grid-cols-[1fr_170px_170px_auto]"><input className="input" value={query} onChange={event => setQuery(event.target.value)} placeholder="Nombre o NIT" /><input type="date" className="input" value={range.fechaDesde} onChange={event => setRange({ ...range, fechaDesde: event.target.value })} /><input type="date" className="input" value={range.fechaHasta} onChange={event => setRange({ ...range, fechaHasta: event.target.value })} /><button onClick={search} className="button-primary"><Search className="h-4 w-4" />Buscar</button></section>
        {!!clients.length && <section className="flex flex-wrap gap-2 border bg-white p-4">{clients.map(client => <button key={client.idCliente} onClick={() => consult(client)} className="rounded-md border px-3 py-2 text-sm">{client.cliente} · {money.format(client.saldoPendiente)}</button>)}</section>}
        {state?.resumen && <><section className="grid gap-3 sm:grid-cols-3"><Metric label="Límite" value={money.format(state.resumen.limiteCredito)} /><Metric label="Pendiente" value={money.format(state.resumen.saldoPendiente)} /><Metric label="Disponible" value={money.format(state.resumen.creditoDisponible)} /></section><section className="border bg-white"><header className="flex justify-between border-b p-4"><div><b>{state.resumen.cliente}</b><p className="text-sm text-slate-500">{state.resumen.nit || 'CF'}</p></div><button onClick={excel} className="button-secondary"><Download className="h-4 w-4" />Excel</button></header><Table headers={['Fecha', 'Movimiento', 'Documento', 'Vencimiento', 'Cargo', 'Pagado', 'Estado']} empty={!state.movimientos.length}>{state.movimientos.map(row => <tr key={`${row.tipo}-${row.idMovimiento}`}><Cell>{formatDate(row.fecha)}</Cell><Cell>{row.tipo}</Cell><Cell>{row.documento}</Cell><Cell>{formatDate(row.fechaVencimiento)}</Cell><Cell right>{money.format(row.debito)}</Cell><Cell right>{money.format(row.credito)}</Cell><Cell>{row.estado}</Cell></tr>)}</Table></section></>}
    </Page>;
}

function PagarAbono({ branch }) {
    const [query, setQuery] = useState(''); const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ monto: '', metodoPago: 'efectivo', referencia: '' }); const [confirm, setConfirm] = useState(false); const [notice, setNotice] = useState(null);
    const search = async () => { const response = await axiosClient.get('/cobros/cuentas-pendientes', { params: { idSucursal: branch, query } }); setRows(response.data.data || []); setSelected(null); };
    const requestPay = () => { const amount = Number(form.monto); if (!selected || amount <= 0 || amount > selected.saldoPendiente) return setNotice({ type: 'warning', message: 'Selecciona una cuenta e ingresa un monto válido.' }); setConfirm(true); };
    const pay = async () => { setConfirm(false); try { const response = await axiosClient.post('/cobros/abonos', { idCuenta: selected.idCuenta, idSucursal: Number(branch), monto: Number(form.monto), metodoPago: form.metodoPago, referencia: form.referencia }); const pdf = await axiosClient.get(`/cobros/abonos/${response.data.data.idAbono}/pdf`, { responseType: 'blob' }); window.open(URL.createObjectURL(pdf.data), '_blank'); setNotice({ type: 'success', message: 'Abono registrado.' }); setForm({ monto: '', metodoPago: 'efectivo', referencia: '' }); await search(); } catch (error) { setNotice({ type: 'error', message: error.response?.data?.message || 'No fue posible registrar el abono.' }); } };
    return <Page title="Pagar abono"><NotificationToast notification={notice} onClose={() => setNotice(null)} /><SearchBar value={query} setValue={setQuery} search={search} /><section className="grid gap-5 xl:grid-cols-[1fr_350px]"><Table headers={['Cliente', 'Nota de crédito', 'Próximo pago', 'Cuotas', 'Pendiente']} empty={!rows.length}>{rows.map(row => <tr key={row.idCuenta} onClick={() => setSelected(row)} className={`cursor-pointer ${selected?.idCuenta === row.idCuenta ? 'bg-teal-50' : 'hover:bg-slate-50'}`}><Cell strong>{row.cliente}</Cell><Cell>{row.notaCredito}</Cell><Cell>{formatDate(row.proximoVencimiento)}</Cell><Cell>{row.cuotasPagadas}/{row.numeroCuotas}</Cell><Cell right strong>{money.format(row.saldoPendiente)}</Cell></tr>)}</Table><FormPanel title="Registrar pago" selected={selected}><Field label="Monto *"><input type="number" className="input" min="0.01" step="0.01" value={form.monto} onChange={event => setForm({ ...form, monto: event.target.value })} /></Field><Field label="Forma de pago"><select className="input" value={form.metodoPago} onChange={event => setForm({ ...form, metodoPago: event.target.value })}><option value="efectivo">Efectivo</option><option value="transferencia">Transferencia</option><option value="cheque">Cheque</option><option value="tarjeta">Tarjeta</option></select></Field><Field label="Referencia"><input className="input" value={form.referencia} onChange={event => setForm({ ...form, referencia: event.target.value })} /></Field><button onClick={requestPay} className="button-primary w-full">Registrar abono</button></FormPanel></section>{confirm && <Confirm text={`Registrar ${money.format(Number(form.monto))} para ${selected.cliente}.`} close={() => setConfirm(false)} accept={pay} />}</Page>;
}

function Autorizar() {
    const [query, setQuery] = useState(''); const [rows, setRows] = useState([]); const [selected, setSelected] = useState(null); const [form, setForm] = useState({ limiteCredito: '', diasMaximosPago: 30, fechaVencimientoAutorizacion: '', observaciones: '', activo: true }); const [notice, setNotice] = useState(null);
    const search = async () => { const response = await axiosClient.get('/cobros/autorizaciones', { params: { query } }); setRows(response.data.data || []); };
    const choose = row => { setSelected(row); setForm({ limiteCredito: row.limiteCredito || '', diasMaximosPago: row.diasMaximosPago || 30, fechaVencimientoAutorizacion: row.fechaVencimientoAutorizacion?.slice(0, 10) || '', observaciones: row.observaciones || '', activo: row.idClienteCredito ? row.activo : true }); };
    const save = async () => { try { await axiosClient.post('/cobros/autorizaciones', { idCliente: selected.idCliente, limiteCredito: Number(form.limiteCredito), diasMaximosPago: Number(form.diasMaximosPago), fechaVencimientoAutorizacion: form.fechaVencimientoAutorizacion || null, observaciones: form.observaciones, activo: form.activo }); setNotice({ type: 'success', message: 'Autorización guardada.' }); await search(); } catch (error) { setNotice({ type: 'error', message: error.response?.data?.message || 'No fue posible guardar.' }); } };
    return <Page title="Autorizar crédito"><NotificationToast notification={notice} onClose={() => setNotice(null)} /><SearchBar value={query} setValue={setQuery} search={search} /><section className="grid gap-5 xl:grid-cols-[1fr_380px]"><Table headers={['Cliente', 'NIT', 'Límite', 'Deuda', 'Estado']} empty={!rows.length}>{rows.map(row => <tr key={row.idCliente} onClick={() => choose(row)} className={`cursor-pointer ${selected?.idCliente === row.idCliente ? 'bg-teal-50' : 'hover:bg-slate-50'}`}><Cell strong>{row.cliente}</Cell><Cell>{row.nit || 'CF'}</Cell><Cell right>{row.limiteCredito ? money.format(row.limiteCredito) : '—'}</Cell><Cell right>{money.format(row.saldoPendiente)}</Cell><Cell>{row.idClienteCredito ? row.activo ? 'Autorizado' : 'Inactivo' : 'Sin autorización'}</Cell></tr>)}</Table><FormPanel title="Autorización" selected={selected}><Field label="Límite *"><input type="number" className="input" value={form.limiteCredito} onChange={event => setForm({ ...form, limiteCredito: event.target.value })} /></Field><Field label="Días máximos de pago *"><input type="number" className="input" value={form.diasMaximosPago} onChange={event => setForm({ ...form, diasMaximosPago: event.target.value })} /></Field><Field label="Vigencia"><input type="date" className="input" value={form.fechaVencimientoAutorizacion} onChange={event => setForm({ ...form, fechaVencimientoAutorizacion: event.target.value })} /></Field><Field label="Observaciones"><textarea className="input h-20 py-2" value={form.observaciones} onChange={event => setForm({ ...form, observaciones: event.target.value })} /></Field><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.activo} onChange={event => setForm({ ...form, activo: event.target.checked })} />Autorizado</label><button onClick={save} className="button-primary w-full">Guardar</button></FormPanel></section></Page>;
}

function Page({ title, children }) { return <div className="space-y-5"><header className="page-title p-5"><h1 className="text-2xl font-bold">{title}</h1></header>{children}</div>; }
function SearchBar({ value, setValue, search, loading, children }) { return <section className="flex flex-wrap items-center gap-3 border bg-white p-5"><input className="input min-w-64 flex-1" value={value} onChange={event => setValue(event.target.value)} placeholder="Nombre, NIT o documento" />{children}<button onClick={search} disabled={loading} className="button-primary"><Search className="h-4 w-4" />Buscar</button></section>; }
function Table({ headers, children, empty }) { return <div className="overflow-x-auto border bg-white"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-100 text-left"><tr>{headers.map((header,index) => <th key={index} className="p-4">{header}</th>)}</tr></thead><tbody className="divide-y">{children}</tbody></table>{empty && <Empty />}</div>; }
function Cell({ children, right, strong }) { return <td className={`p-4 ${right ? 'text-right' : ''} ${strong ? 'font-bold' : ''}`}>{children}</td>; }
function Metric({ label, value }) { return <div className="border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-xl font-bold">{value}</p></div>; }
function Field({ label, children }) { return <label className="block text-sm font-semibold"><span className="mb-1 block">{label}</span>{children}</label>; }
function FormPanel({ title, selected, children }) { return <aside className="h-fit border bg-white p-5"><h2 className="font-bold">{title}</h2>{selected ? <div className="mt-4 space-y-4"><p className="text-sm font-semibold">{selected.cliente}</p>{children}</div> : <p className="mt-4 text-sm text-slate-500">Selecciona una fila.</p>}</aside>; }
function Empty({ text = 'Sin resultados. Utiliza los campos de búsqueda.' }) { return <p className="p-8 text-center text-sm text-slate-500">{text}</p>; }
function Confirm({ text, close, accept }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md border bg-white p-6"><div className="flex justify-between"><b>Confirmar abono</b><button onClick={close}><X className="h-5 w-5" /></button></div><p className="mt-4 text-sm">{text}</p><div className="mt-6 flex justify-end gap-2"><button onClick={close} className="button-secondary">Cancelar</button><button onClick={accept} className="button-primary">Confirmar</button></div></div></div>; }
function download(blob, name) { const anchor = document.createElement('a'); anchor.href = URL.createObjectURL(blob); anchor.download = name; anchor.click(); }
