import { useCallback, useEffect, useMemo, useState } from 'react';
import { X } from 'lucide-react';
import axiosClient from '../api/axiosClient';
import { useAuth } from '../context/AuthContext';
import NotificationToast from '../components/NotificationToast';
const money = new Intl.NumberFormat('es-GT', { style: 'currency', currency: 'GTQ' });
export default function ControlCajaPage({ mode = 'current' }) {
    const { selectedSucursalId } = useAuth(); const [data, setData] = useState(null); const [movements, setMovements] = useState([]); const [closures, setClosures] = useState([]); const [amount, setAmount] = useState(''); const [notes, setNotes] = useState(''); const [notification, setNotification] = useState(null); const [summary, setSummary] = useState(null);
    const load = useCallback(async () => { if (!selectedSucursalId) return; if (mode === 'closures') { const response = await axiosClient.get('/operaciones/caja/cierres', { params: { idSucursal: selectedSucursalId } }); setClosures(response.data.data || []); return; } const [state, list] = await Promise.all([axiosClient.get('/operaciones/caja', { params: { idSucursal: selectedSucursalId } }), axiosClient.get('/operaciones/caja/movimientos', { params: { idSucursal: selectedSucursalId } })]); setData(state.data.data); setMovements(list.data.data || []); }, [selectedSucursalId, mode]);
    useEffect(() => { load(); }, [load]);
    const expected = useMemo(() => data ? data.montoApertura + data.ventasEfectivo - data.comprasEfectivo : 0, [data]);
    const action = async type => { try { const response = await axiosClient.post(`/operaciones/caja/${type}`, { idSucursal: Number(selectedSucursalId), monto: Number(amount), observaciones: notes }); if (type === 'cerrar') setSummary(response.data.data); setAmount(''); setNotes(''); setNotification({ type: 'success', message: `Caja ${type === 'abrir' ? 'abierta' : 'cerrada'} correctamente.` }); load(); } catch (error) { setNotification({ type: 'error', message: error.response?.data?.message || 'No fue posible actualizar la caja.' }); } };
    if (mode === 'closures') return <Page title="Cierres de caja"><section className="overflow-x-auto border bg-white"><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-4">Cierre</th><th>Usuario</th><th>Fecha</th><th className="text-right">Esperado</th><th className="text-right">Contado</th><th className="p-4 text-right">Diferencia</th></tr></thead><tbody className="divide-y">{closures.map(row => <tr key={row.idSesion}><td className="p-4"><b>{row.numeroCierre}</b><small className="block">Apertura {new Date(row.fechaApertura).toLocaleString('es-GT')}</small></td><td>{row.usuario}</td><td>{new Date(row.fechaCierre).toLocaleString('es-GT')}</td><td className="text-right">{money.format(row.montoEsperado)}</td><td className="text-right">{money.format(row.montoCierre)}</td><td className={`p-4 text-right font-bold ${row.diferencia < 0 ? 'text-red-600' : 'text-emerald-700'}`}>{money.format(row.diferencia)}</td></tr>)}</tbody></table></section></Page>;
    return <Page title="Caja"><NotificationToast notification={notification} onClose={() => setNotification(null)} />{data ? <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Card label="Apertura" value={data.montoApertura} /><Card label="Efectivo" value={data.ventasEfectivo} /><Card label="Tarjeta" value={data.ventasTarjeta} /><Card label="Transferencia" value={data.ventasTransferencia} /><Card label="Crédito" value={data.ventasCredito} /><Card label="Total ventas" value={data.ventasTotales} /></section><div className="grid gap-5 xl:grid-cols-[1fr_360px]"><section className="overflow-x-auto border bg-white"><h2 className="border-b p-4 font-bold">Movimientos</h2><table className="w-full text-sm"><thead className="bg-slate-100 text-left"><tr><th className="p-4">Documento</th><th>Fecha</th><th>Método</th><th>Estado</th><th className="p-4 text-right">Monto</th></tr></thead><tbody className="divide-y">{movements.map((row, index) => <tr key={`${row.numero}-${index}`}><td className="p-4"><b>{row.numero}</b><small className="block">{row.tipo}</small></td><td>{new Date(row.fecha).toLocaleString('es-GT')}</td><td className="capitalize">{row.metodoPago}</td><td>{row.estado}</td><td className={`p-4 text-right font-bold ${row.monto < 0 ? 'text-red-600' : ''}`}>{money.format(row.monto)}</td></tr>)}</tbody></table></section><aside className="h-fit border bg-white p-5"><h2 className="font-bold">Cuadre de efectivo</h2><p className="mt-3 flex justify-between"><span>Ventas efectivo</span><b>{money.format(data.ventasEfectivo)}</b></p><p className="mt-2 flex justify-between"><span>Compras efectivo</span><b className="text-red-600">-{money.format(data.comprasEfectivo)}</b></p><p className="mt-3 flex justify-between border-t pt-3"><span>Esperado</span><b>{money.format(expected)}</b></p><input type="number" min="0" step=".01" className="input mt-4" value={amount} onChange={event => setAmount(event.target.value)} placeholder="Efectivo contado" /><p className="mt-2 text-sm">Diferencia: <b>{money.format((Number(amount) || 0) - expected)}</b></p><textarea className="input mt-3 h-20 py-2" value={notes} onChange={event => setNotes(event.target.value)} placeholder="Observaciones" /><button disabled={amount === ''} onClick={() => action('cerrar')} className="mt-4 w-full rounded-md bg-slate-800 py-3 font-bold text-white disabled:opacity-50">Cerrar caja</button></aside></div></> : <section className="mx-auto max-w-md border bg-white p-6"><h2 className="font-bold">Abrir caja</h2><p className="text-sm text-slate-500">{new Date().toLocaleString('es-GT')}</p><input type="number" min="0" step=".01" className="input mt-4" value={amount} onChange={event => setAmount(event.target.value)} placeholder="Monto inicial" /><button disabled={amount === ''} onClick={() => action('abrir')} className="mt-3 w-full rounded-md bg-brand-teal py-3 font-bold text-white">Abrir caja</button></section>}{summary && <CloseSummary data={summary} close={() => setSummary(null)} />}</Page>;
}
function Page({ title, children }) { return <div className="space-y-5"><header className="page-title p-5"><h1 className="text-2xl font-bold">{title}</h1></header>{children}</div>; }
function Card({ label, value }) { return <div className="border bg-white p-4"><p className="text-sm text-slate-500">{label}</p><b className="mt-2 block text-xl">{money.format(value || 0)}</b></div>; }
function CloseSummary({ data, close }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md border bg-white p-6 shadow-xl"><div className="flex justify-between"><h2 className="text-lg font-bold">Cierre completado</h2><button onClick={close}><X /></button></div><p className="mt-2 text-brand-teal">{data.numeroCierre}</p><p className="text-sm">{new Date(data.fechaCierre).toLocaleString('es-GT')}</p><div className="mt-5 space-y-2"><p className="flex justify-between"><span>Esperado</span><b>{money.format(data.montoEsperado)}</b></p><p className="flex justify-between"><span>Contado</span><b>{money.format(data.montoCierre)}</b></p><p className="flex justify-between border-t pt-2"><span>Diferencia</span><b>{money.format(data.diferencia)}</b></p></div><button onClick={close} className="mt-5 w-full rounded-md bg-brand-teal py-2 font-bold text-white">Aceptar</button></div></div>; }
