import { Fragment, useCallback, useEffect, useState } from 'react';
import { ChevronDown, ChevronRight, Search, X } from 'lucide-react';
import axiosClient from '../api/axiosClient';
import NotificationToast from '../components/NotificationToast';

const emptySupplier = { nombre: '', telefono: '', direccion: '' };
const emptyProduct = { codigo: '', nombre: '', descripcion: '', precio: '' };
export default function ProveedoresPage() {
    const [query, setQuery] = useState(''); const [suppliers, setSuppliers] = useState([]); const [selected, setSelected] = useState(null); const [products, setProducts] = useState([]); const [openSupplier, setOpenSupplier] = useState(false); const [openProduct, setOpenProduct] = useState(false); const [supplier, setSupplier] = useState(emptySupplier); const [product, setProduct] = useState(emptyProduct); const [notification, setNotification] = useState(null);
    const load = useCallback(async (term = '') => { const response = await axiosClient.get('/inventario/proveedores', { params: { query: term } }); setSuppliers(response.data.data || []); }, []);
    useEffect(() => { load(); }, [load]);
    useEffect(() => { const timer = window.setTimeout(() => load(query), 300); return () => window.clearTimeout(timer); }, [query, load]);
    const toggle = async row => { if (selected?.idProveedor === row.idProveedor) { setSelected(null); setProducts([]); return; } setSelected(row); const response = await axiosClient.get(`/inventario/proveedores/${row.idProveedor}/productos`); setProducts(response.data.data || []); };
    const saveSupplier = async event => { event.preventDefault(); try { await axiosClient.post('/inventario/proveedores', supplier); setOpenSupplier(false); setSupplier(emptySupplier); await load(); setNotification({ type: 'success', message: 'Proveedor creado.' }); } catch (error) { setNotification({ type: 'error', message: error.response?.data?.message || 'No fue posible crear el proveedor.' }); } };
    const saveProduct = async event => { event.preventDefault(); try { await axiosClient.post('/inventario/entrada/productos', { ...product, idProveedor: selected.idProveedor, precio: Number(product.precio) }); setOpenProduct(false); setProduct(emptyProduct); await toggleReload(selected); setNotification({ type: 'success', message: 'Producto creado y asignado.' }); } catch (error) { setNotification({ type: 'error', message: error.response?.data?.message || 'No fue posible crear el producto.' }); } };
    const toggleReload = async row => { const response = await axiosClient.get(`/inventario/proveedores/${row.idProveedor}/productos`); setProducts(response.data.data || []); };
    return <div className="space-y-5">
        <NotificationToast notification={notification} onClose={() => setNotification(null)} />
        <header className="border bg-white p-5"><div className="flex items-center justify-between gap-3"><h1 className="text-2xl font-bold">Proveedores</h1><button onClick={() => setOpenSupplier(true)} className="rounded-md bg-brand-teal px-4 py-2 font-semibold text-white">Nuevo proveedor</button></div></header>
        <section className="border bg-white"><div className="relative border-b p-4"><Search className="absolute left-7 top-7 h-4 w-4 text-slate-400" /><input className="input pl-10" value={query} onChange={event => setQuery(event.target.value)} placeholder="Nombre o teléfono" /></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="bg-slate-100 text-left"><tr><th className="w-12 p-4" /><th>Proveedor</th><th>Teléfono</th><th>Dirección</th><th className="p-4 text-right">Productos</th></tr></thead><tbody className="divide-y">{suppliers.map(row => <Fragment key={row.idProveedor}><tr className={selected?.idProveedor === row.idProveedor ? 'bg-teal-50' : ''}><td className="p-4"><button onClick={() => toggle(row)} aria-label="Ver productos">{selected?.idProveedor === row.idProveedor ? <ChevronDown className="h-4 w-4" /> : <ChevronRight className="h-4 w-4" />}</button></td><td className="font-semibold">{row.nombre}</td><td>{row.telefono || '—'}</td><td>{row.direccion || '—'}</td><td className="p-4 text-right"><button onClick={() => toggle(row)} className="rounded-md border px-3 py-1.5">{selected?.idProveedor === row.idProveedor ? 'Ocultar' : 'Ver productos'}</button></td></tr>{selected?.idProveedor === row.idProveedor && <tr><td colSpan="5" className="bg-slate-50 p-0"><div className="flex items-center justify-between border-b px-5 py-3"><b>Productos de {row.nombre}</b><button onClick={() => setOpenProduct(true)} className="rounded-md bg-brand-teal px-3 py-2 text-sm font-semibold text-white">Crear producto</button></div><table className="w-full text-sm"><thead><tr className="text-left text-slate-500"><th className="px-8 py-3">Código</th><th>Producto</th><th>Descripción</th><th className="px-8 text-right">Precio</th></tr></thead><tbody className="divide-y">{products.map(item => <tr key={item.idProducto}><td className="px-8 py-3">{item.codigo || `#${item.idProducto}`}</td><td className="font-semibold">{item.nombre}</td><td>{item.descripcion || '—'}</td><td className="px-8 text-right">Q {Number(item.precio).toFixed(2)}</td></tr>)}</tbody></table>{!products.length && <p className="px-8 py-6 text-sm text-slate-500">Este proveedor no tiene productos asignados.</p>}</td></tr>}</Fragment>)}</tbody></table></div>{!suppliers.length && <p className="p-8 text-center text-sm text-slate-500">No hay proveedores.</p>}</section>
        {openSupplier && <Modal title="Nuevo proveedor" close={() => setOpenSupplier(false)}><form onSubmit={saveSupplier} className="space-y-3"><Input required label="Nombre *" value={supplier.nombre} set={value => setSupplier({ ...supplier, nombre: value })} /><Input label="Teléfono" value={supplier.telefono} set={value => setSupplier({ ...supplier, telefono: value })} /><Input label="Dirección" value={supplier.direccion} set={value => setSupplier({ ...supplier, direccion: value })} /><Save /></form></Modal>}
        {openProduct && <Modal title={`Producto de ${selected?.nombre}`} close={() => setOpenProduct(false)}><form onSubmit={saveProduct} className="space-y-3"><Input label="Código" value={product.codigo} set={value => setProduct({ ...product, codigo: value })} /><Input required label="Nombre *" value={product.nombre} set={value => setProduct({ ...product, nombre: value })} /><Input label="Descripción" value={product.descripcion} set={value => setProduct({ ...product, descripcion: value })} /><Input required type="number" min="0" step=".01" label="Precio de venta *" value={product.precio} set={value => setProduct({ ...product, precio: value })} /><Save /></form></Modal>}
    </div>;
}
function Modal({ title, close, children }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-lg border bg-white p-6 shadow-xl"><div className="mb-5 flex justify-between"><h2 className="text-lg font-bold">{title}</h2><button onClick={close}><X /></button></div>{children}</div></div>; }
function Input({ label, value, set, ...props }) { return <label className="block text-sm font-semibold">{label}<input {...props} className="input mt-1" value={value} onChange={event => set(event.target.value)} /></label>; }
function Save() { return <button className="w-full rounded-md bg-brand-teal py-3 font-bold text-white">Guardar</button>; }
